// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntwzllhfsiyzlcukjlnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50d3psbGhmc2l5emxjdWtqbG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTI1NzAsImV4cCI6MjA3MDAyODU3MH0.3mSRdjhboQ0wVQhPjg4fE0J3PWHy42pNVk0pn38CtJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});